#!/bin/bash

on=9
lon=8

while [ 1 ];
do
	ping -c 1 -w 1 FireTV-Wohnzimmer
	t1=$?
	ping -c 1 -w 1 FireTV-Wohnzimmer
	t2=$?
	ping -c 1 -w 1 FireTV-Wohnzimmer
	t3=$?
	if [ $[ $t1 + $t2 + $t3 ] -lt 3 ]; then
		on=1
	else
		on=0
	fi
	if [ $on -ne $lon ]; then
		if [ $on -eq 0 ]; then
			curl "http://192.168.178.29:8080/goform/formiPhoneAppPower.xml?1+PowerStandby"
		fi
	fi
	lon=$on
	sleep 7
done
