#!/bin/bash

AVR_IP="192.168.178.29"
DELAY=7
lvon=9

function setVon {
	if [ "$1" = "$lvon" ]; then
		return
	fi
	redis-cli -h dax set "AVR-Video-Active/v0/target" "$1"
	lvon="$1"
}

while [ 1 ];
do
	ret=$(curl -s http://$AVR_IP:8080/goform/formMainZone_MainZoneXmlStatusLite.xml)
	sosel=$(echo "$ret" | grep InputFuncSelect | sed -e 's/^.*<value>//' -e 's/<.*$//')
	pow=$(echo "$ret" | grep Power | sed -e 's/^.*<value>//' -e 's/<.*$//')
	if [ "$pow" != "ON" ]; then
		setVon 0
		sleep $DELAY
		continue
	fi
	von=0
	if [ "$sosel" = "BD" ]; then
		von=1
	fi
	if [ "$sosel" = "SAT/CBL" ]; then
		von=1
	fi
	if [ "$sosel" = "MPLAY" ]; then
		von=1
	fi
	if [ "$sosel" = "AUX1" ]; then
		von=1
	fi
	echo "$sosel $von"
	setVon "$von"
	sleep $DELAY
done
